import { NgModule } from '@angular/core';

import {
  MatToolbarModule,
  MatIconModule,
  MatButtonModule,
  MatCardModule,
  MatCheckboxModule,
  MatFormFieldModule,
  MatStepperModule,
  MatInputModule,
  MatSelectModule,
  MatBadgeModule,
  MatTabsModule,
  MatMenuModule,
  MatDatepickerModule,
  MatChipsModule,
  MatGridListModule,
  MatExpansionModule,
  MatListModule,
  MatProgressSpinnerModule,
  MatSidenavModule,
  MatRadioModule,
  MatProgressBarModule,
  MatTableModule,
  MatSortModule,
  MatTreeModule,
  MatTooltipModule,
  MatNativeDateModule
} from '@angular/material';
import { DragDropModule } from '@angular/cdk/drag-drop';

@NgModule({
  imports: [
    MatToolbarModule,
    MatIconModule,
    MatCheckboxModule,
    MatButtonModule,
    MatTooltipModule,
    MatDatepickerModule,
    MatTreeModule,
    MatCardModule,
    DragDropModule,
    MatNativeDateModule,
    MatFormFieldModule,
    MatStepperModule,
    MatInputModule,
    MatSelectModule,
    MatBadgeModule,
    MatTabsModule,
    MatMenuModule,
    MatChipsModule,
    MatGridListModule,
    MatExpansionModule,
    MatListModule,
    MatProgressSpinnerModule,
    MatSidenavModule,
    MatToolbarModule,
    MatRadioModule,
    MatProgressBarModule,
    MatTableModule,
    MatExpansionModule,
    MatSortModule
  ],

  exports: [
    MatToolbarModule,
    MatIconModule,
    MatTooltipModule,
    MatTreeModule,
    MatButtonModule,
    MatCardModule,
    MatNativeDateModule,
    MatDatepickerModule,
    DragDropModule,
    MatCheckboxModule,
    MatFormFieldModule,
    MatStepperModule,
    MatInputModule,
    MatSelectModule,
    MatBadgeModule,
    MatTabsModule,
    MatMenuModule,
    MatChipsModule,
    MatGridListModule,
    MatExpansionModule,
    MatListModule,
    MatProgressSpinnerModule,
    MatSidenavModule,
    MatToolbarModule,
    MatRadioModule,
    MatProgressBarModule,
    MatTableModule,
    MatExpansionModule,
    MatSortModule
  ]
})

export class MaterialModule { }
